import Head from 'next/head'
import Embudo from '../src/components/embudo'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Prime Capital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <Embudo />
    </div>
  )
}
