import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Victor Alvarez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <div className='section-1 w-full px-auto pb-20 lg:pb-48 flex flex-col justify-center items-center text-white relative'>
        <div className='flex flex-col items-center lg:px-32 md:px-18 sm:px-10 px-5 py-36 gap-5 container'>
          <div className='flex justify-center'>
            <Image src={"/assets/logo.png"} alt="Logo" width={150} height={150} />
          </div>
          <h1 className='text-center xl:text-5xl lg:text-4xl md:text-4xl sm:text-3xl text-2xl'>Opera 100% en automático y obtén hasta un 30% mensual</h1>
          <h2 className='text-center md:text-xl sm:text-lg text-md leading-loose'>
            Opera en el mercado de Forex, de lunes a viernes 100% en automático.<br />
            Creado para principiantes o personas experimentadas por igual, es fácil de configurar y obtienes resultados en <span className='underline decoration-red-500 underline-offset-4'>menos de 24 horas.</span>
          </h2>
        </div>
        <div className="elementor-shape elementor-shape-bottom" data-negative="false">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">
            <path className="elementor-shape-fill" d="M0,6V0h1000v100L0,6z"></path>
          </svg>
        </div>
      </div>

      <div className='section-2 w-full px-auto flex justify-center bg-white text-black relative'>
        <div className='flex flex-col items-center lg:px-32 md:px-18 sm:px-10 px-5 py-20 gap-5 container'>
          <h1 className='text-center xl:text-5xl lg:text-4xl md:text-4xl sm:text-3xl text-2xl'>¿Por qué trabajar con este Bot?</h1>
          <h2 className='text-center md:text-xl sm:text-lg text-md leading-loose'>Estos son los 3 beneficios más importantes.</h2>
          <div className='grid grid-cols-3 xl:gap-40 lg:gap-20 gap-5 mt-5'>
            <div className='flex flex-col items-start'>
              <div className='flex w-full justify-center mb-2'>
                <Image src="/assets/burn-icon.png" width={50} height={50} alt="burn-icon" />
              </div>
              <span className='block w-full font-bold leading-loose text-xl text-center'>No quemas cuentas</span>
              <span className='block leading-relaxed text-center mt-2'>Usa algoritmos, redes neuronales, inteligencia artificial cuántica, para detectar el mejor momento de entrada y salida, de esta forma una operativa se cierra en cuestión de segundos</span>
            </div>
            <div className='flex flex-col items-start'>
              <div className='flex w-full justify-center mb-2'>
                <Image src="/assets/devaluation-icon.png" width={50} height={50} alt="devaluation-icon" />
              </div>
              <span className='block w-full font-bold leading-loose text-xl text-center'>No hay devaluación</span>
              <span className='block leading-relaxed text-center mt-2'>Sin riesgo de perdida, utiliza Inteligencia Artificial y opera en automático en USDT, todas las ganancias son en USDT. Verás como tu capital se incrementa día a día.</span>
            </div>
            <div className='flex flex-col items-start'>
              <div className='flex w-full justify-center mb-2'>
                <Image src="/assets/easy-icon.png" width={50} height={50} alt="easy-icon" />
              </div>
              <span className='block w-full font-bold leading-loose text-xl text-center'>Fácil de conectar</span>
              <span className='block leading-relaxed text-center mt-2'>Usa algoritmos, redes neuronales, inteligencia artificial cuántica, para detectar el mejor momento de entrada y salida, de esta forma una operativa se cierra en cuestión de segundos</span>
            </div>
          </div>
        </div>
        <div className="elementor-shape elementor-shape-top" data-negative="false">
			    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">
	          <path className="elementor-shape-fill" d="M0,6V0h1000v100L0,6z"></path>
          </svg>
        </div>
      </div>

      <div className='section-3 w-full px-auto flex flex-col justify-center text-white relative'>
        <div className='flex flex-col items-center lg:px-32 md:px-18 sm:px-10 px-5 py-36 gap-5 container'>
          
        </div>
      </div>
    </div>
  )
}
